# Generated by Django 4.1.2 on 2022-10-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
