# Generated by Django 4.1.2 on 2022-10-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_facebook', models.PositiveSmallIntegerField()),
                ('time_whatsapp', models.PositiveSmallIntegerField()),
                ('time_twitter', models.PositiveSmallIntegerField()),
                ('time_instagram', models.PositiveSmallIntegerField()),
                ('time_tiktok', models.PositiveSmallIntegerField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.people')),
            ],
        ),
    ]
